apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app2
---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app3
